name: Validate Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Marketplace and Plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate marketplace.json
        run: npm run validate:marketplace

      - name: Validate plugins
        run: npm run validate:plugins

      - name: Upload validation results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: |
            **/*.log
          retention-days: 7

  lint-json:
    name: Lint JSON Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate marketplace.json syntax
        run: |
          if ! python -m json.tool .claude-plugin/marketplace.json > /dev/null; then
            echo "❌ marketplace.json is not valid JSON"
            exit 1
          fi
          echo "✅ marketplace.json is valid JSON"

      - name: Validate all plugin.json files
        run: |
          EXIT_CODE=0
          for file in $(find plugins -name "plugin.json"); do
            if ! python -m json.tool "$file" > /dev/null 2>&1; then
              echo "❌ Invalid JSON: $file"
              EXIT_CODE=1
            else
              echo "✅ Valid JSON: $file"
            fi
          done
          exit $EXIT_CODE

  check-structure:
    name: Check Directory Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify required files exist
        run: |
          EXIT_CODE=0

          # Check marketplace.json
          if [ ! -f ".claude-plugin/marketplace.json" ]; then
            echo "❌ Missing .claude-plugin/marketplace.json"
            EXIT_CODE=1
          else
            echo "✅ Found marketplace.json"
          fi

          # Check documentation
          for doc in README.md CONTRIBUTING.md LICENSE; do
            if [ ! -f "$doc" ]; then
              echo "❌ Missing $doc"
              EXIT_CODE=1
            else
              echo "✅ Found $doc"
            fi
          done

          # Check documentation directory
          for doc in docs/PLUGIN_GUIDELINES.md docs/STRUCTURE.md docs/TESTING.md; do
            if [ ! -f "$doc" ]; then
              echo "❌ Missing $doc"
              EXIT_CODE=1
            else
              echo "✅ Found $doc"
            fi
          done

          # Check schemas
          for schema in schemas/marketplace-schema.json schemas/plugin-manifest-schema.json; do
            if [ ! -f "$schema" ]; then
              echo "❌ Missing $schema"
              EXIT_CODE=1
            else
              echo "✅ Found $schema"
            fi
          done

          # Check scripts
          for script in scripts/validate-marketplace.js scripts/validate-plugin.js scripts/test-plugins.sh; do
            if [ ! -f "$script" ]; then
              echo "❌ Missing $script"
              EXIT_CODE=1
            else
              echo "✅ Found $script"
            fi
          done

          exit $EXIT_CODE

      - name: Check category directories
        run: |
          EXIT_CODE=0

          for category in general meta-agents specialized; do
            if [ ! -d "plugins/$category" ]; then
              echo "❌ Missing plugins/$category directory"
              EXIT_CODE=1
            else
              echo "✅ Found plugins/$category directory"
            fi
          done

          exit $EXIT_CODE
